### ISSUE TITLE
Wrong mention to `global variable` 

### ISSUE THREAD

**Issue by cbeltrao** [LearnWeb3DAO/Solidity#7]
Hey guys, I found what I believe is a wrong mention to a variable type on line 124:

```It takes in a uint and sets the global variable num.```

Wouldn't it be a `state` variable?

**Comment by Sneh1999** [comment]
can you create a pr for this, cause I am not sure which line number you are talking about? 
Thanks a lot

**Comment by victorknox** [comment]
As @cbeltrao has mentioned, it is on line 124, where Functions and Loops are being explained
Also, there is a slight grammatical error 

This is the change I propose:

  ```
        Name of the function is set.
        It takes in a uint and sets the global variable num.
        It is a declared as a public function meaning
        it can be called from within the contract and also externally.
 ```
        Name of the function is set.
        It takes in a uint and sets the state variable num.
        It is declared as a public function meaning
        it can be called from within the contract and also externally.
